dormlab/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('management.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }
        )
    ]

admin.site.site_header = 'Dormlab-Admin'

management/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_home, name='user_index'),
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.my_logout, name='logout'),
    path('register/', views.register_page, name='register_page'),
    path('annouce/', views.user_annouce, name='user_annouce'),
    path('bill/', views.user_bill, name='user_bill'),
    path('payment/', views.user_payment, name='user_payment'),
    path('report/', views.user_report, name='user_report'),
    path('bill/detail/123', views.user_detail, name='user_detail'),
    path('contract/', views.contract, name='contract'),
]

management/models.py
from django.db import models
from django.contrib.auth.models import User 

# from PIL import Image

import datetime

class Room(models.Model):
    room_number = models.CharField(max_length=10)  # also Room Number
    room_floor = models.IntegerField(default=1)
    room_rate = models.DecimalField(max_digits=10, decimal_places=3)

    STATUS = (
        ('01','Available'),
        ('02','Full'),
        ('03', 'Booked'),
    )
    status = models.CharField(max_length=2, choices=STATUS, default='01')

    TYPES = (
        ('01', "Fan"),
        ('02', "AirCondition"),
    )
    room_type = models.CharField(max_length=2, choices=TYPES, default='01', verbose_name="ROOM TYPE")

    #foreignKey
    dorm_dorm_id = models.ForeignKey('Dorm', on_delete=models.PROTECT, verbose_name="DORM NAME")
    def __str__(self):
        return "From %s - Room: %s"%(self.dorm_dorm_id,self.room_number)

class Reporting(models.Model):
    report_desc = models.TextField( verbose_name="REPORT DESCRIPTION")
    report_date = models.DateTimeField()

    #foreignKey
    report_type_type_id = models.ForeignKey('Report_type', on_delete=models.PROTECT, verbose_name="REPORT TYPE")
    room_room_id = models.ForeignKey('Room', on_delete=models.PROTECT, verbose_name="DORM - ROOM NUMBER")

class Report_type(models.Model):
    type_name = models.CharField(max_length=100)
    def __str__(self):
        return "%s"%(self.type_name)

class Dorm(models.Model):
    dorm_name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    floor = models.IntegerField(default=1)
    # elec_unit = models.DecimalField(max_digits=10, decimal_places=3)
    # water_unit = models.DecimalField(max_digits=10, decimal_places=3)
    room_amount = models.IntegerField(default=1)
    tel = models.CharField(max_length=10, unique=True, default='0000000000')
    taxid = models.CharField(max_length=255, unique=True, default='000-000')

    def __str__(self):
        return "%s"%(self.dorm_name)


class Employee(User):
    # owner = models.BooleanField(default=False)
    # emp_fname = models.CharField(max_length=255)
    # emp_lname = models.CharField(max_length=255)
    # password = models.CharField(max_length=255)
    emp_phone = models.CharField(max_length=10, unique=True)

    #foreignKey
    # emp_id = models.OneToOneField(User, on_delete=models.PROTECT)
    dorm_dorm_id = models.ForeignKey('Dorm', on_delete=models.PROTECT, verbose_name="DORM NAME")

    class Meta:
        verbose_name = 'Employee'
        verbose_name_plural = 'Employees'
    def __str__(self):
        return "%s"%(self.username)

class Contracting(models.Model):
    #dorm_name = models.CharField(max_length=255)
    #room_number = models.CharField(max_length=10)
    start_date = models.DateField()
    expire_date = models.DateField()
    period = models.IntegerField(default=0)
    deposit = models.DecimalField(max_digits=10, decimal_places=3)
    dmg_deposit = models.DecimalField(max_digits=10, decimal_places=3)

    #foreignKey
    room_room_id = models.ForeignKey(Room, on_delete=models.PROTECT, verbose_name="ROOM NUMBER")
    guest_guest_id = models.ForeignKey('Guest', on_delete=models.PROTECT, verbose_name="GUEST NAME")
    def __str__(self):
        return "%s | GUEST : %s"%( self.room_room_id, self.guest_guest_id)

    def day_now_str(self):
        return int(str(self.start_date)[8:10])
    def day_now_end(self):
        return int(str(self.expire_date)[8:10])

    def month_now_str(self):
        month = {
            '01': 'มกราคม', '02': 'กุมภาพันธ์', '03': 'มีนาคม', '04': 'เมษายน',
            '05': 'พฤษภาคม', '06': 'มิถุนายน', '07': 'กรกฎาคม', '08': 'สิงหาคม',
            '09': 'กันยายน', '10': 'ตุลาคม', '11': 'พฤศจิกายน', '12': 'ธันวาคม'
        }
        return month[str(self.start_date)[5:7]]

    def month_now_end(self):
        month = {
            '01': 'มกราคม', '02': 'กุมภาพันธ์', '03': 'มีนาคม', '04': 'เมษายน',
            '05': 'พฤษภาคม', '06': 'มิถุนายน', '07': 'กรกฎาคม', '08': 'สิงหาคม',
            '09': 'กันยายน', '10': 'ตุลาคม', '11': 'พฤศจิกายน', '12': 'ธันวาคม'
        }
        return month[str(self.expire_date)[5:7]]

    def year_now_str(self):
        return int(str(self.start_date)[:4])+543

    def year_now_end(self):
        return int(str(self.expire_date)[:4])+543

class Guest(User):
    # guest_fname = models.CharField(max_length=255)
    # guest_lname = models.CharField(max_length=255)
    # password = models.CharField(max_length=255)
    # career = models.CharField(max_length=255)
    address = models.TextField()
    line = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=10, unique=True)
    #foreignKey
    # guest_id = models.OneToOneField(User, on_delete=models.PROTECT)
    class Meta:
        verbose_name = 'Guest'
        verbose_name_plural = 'Guests'
    def __str__(self):
        return "%s"%(self.username)

class Parcel(models.Model):
    fname_guest = models.CharField(max_length=255)
    lname_guest = models.CharField(max_length=255)
    arrive_date = models.DateTimeField()
    post_type = models.CharField(max_length=255, null=True)
    packaging = models.CharField(max_length=255, null=True)
    track_number = models.CharField(max_length=13, unique=True)

    #foreignKey
    #guest_guest_id = models.ForeignKey('Guest', on_delete=models.PROTECT)
    def __str__(self):
        return "%s %s"%(self.fname_guest, self.lname_guest)

    def year_now(self):
        return int(str(self.arrive_date)[:4])+543

class Invoice(models.Model):
    invoice_date = models.DateField()
    #dorm_name = models.CharField(max_length=255)
    # room_number = models.CharField(max_length=10)
    month_no = models.CharField(max_length=7)
    total = models.DecimalField(max_digits=10, decimal_places=3, default=0.0)
    STATUS = (
        ('01', 'wait_pay'),
        ('02', 'wait_confirm'),
        ('03', 'conform')
    )
    status = models.CharField(max_length=2, choices=STATUS, default='01')
    #foreignKey
    contracting_contract_id = models.ForeignKey('Contracting', on_delete=models.PROTECT, verbose_name="CONTRACT NAME")
    def __str__(self):
        return "%s | DATE : %s"%(self.contracting_contract_id,str(self.invoice_date)[0:7])
    #yyyy-mm-dd
    def month_now(self):
        month = {
            '01' : 'มกราคม', '02' : 'กุมภาพันธ์', '03' : 'มีนาคม', '04' : 'เมษายน', 
            '05' : 'พฤษภาคม', '06' : 'มิถุนายน', '07' : 'กรกฎาคม', '08' : 'สิงหาคม', 
            '09' : 'กันยายน', '10' : 'ตุลาคม', '11' : 'พฤศจิกายน', '12' : 'ธันวาคม'
        }
        # print(self.invoice_date.strftime[5:7:])
        return month[str(self.invoice_date)[5:7]]
    def year_now(self):
        return int(str(self.invoice_date)[:4])+543
    # class Meta:
    #         proxy = True

class Invoice_detail(models.Model):
    # price = models.DecimalField(max_digits=10, decimal_places=3)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    unit = models.DecimalField(max_digits=10, decimal_places=3)

    #foreignKey
    invoice_invoice_id = models.ForeignKey('Invoice', on_delete=models.PROTECT, verbose_name="GUEST INVOICE")
    expense_exp_id = models.ForeignKey('Expense', on_delete=models.PROTECT, verbose_name="EXPENSE DESCRIPTION")
    # def __str__(self):
    #     return "%.2f "%(self.price*self.unit)

class Expense(models.Model):
    exp_desc = models.TextField(verbose_name="EXPENSE DESCRIPTION")
    price_per_unit = models.DecimalField(max_digits=10, decimal_places=3 )

    #foreignKey
    expense_dorm_id = models.ForeignKey('Dorm', on_delete=models.PROTECT)
    def __str__(self):
        return "%s : %s"%(self.expense_dorm_id, self.exp_desc)

class Payment(models.Model):
    # fname = models.CharField(max_length=255)
    # lname = models.CharField(max_length=255)
    #amount = models.DecimalField(max_digits=10, decimal_places=3)
    payment_datetime = models.DateTimeField()
    bill_picture = models.ImageField(blank=True, null=True,
                                     upload_to="payments_%Y-%m-%D")  # this models need to install pip pillow
    STATUS = (
        ('01', 'Unpaid'),
        ('02', 'Paid')
    )
    payment_desc = models.TextField(verbose_name="PAYMENT DESCRIPTION")
    payment_confirm = models.CharField(
        max_length=2, choices=STATUS, default='01')

    #foreignKey
    payment_guest_id = models.ForeignKey('Guest', on_delete=models.PROTECT, verbose_name="GUEST NAME")

class New(models.Model):
    news_title = models.CharField(max_length=255)
    news_content =  models.TextField()

    #foreignKey
    dorm_dorm_id = models.ForeignKey('Dorm', on_delete=models.PROTECT)
    def __str__(self):
        return "%s "%(self.dorm_dorm_id)

management/forms.py
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .models import Payment, Reporting, Guest, Employee
from django.contrib.auth.forms import UserCreationForm

class GuestPaymentForm(forms.ModelForm):
    bill_attr = {'type' :"file", 'class': "custom-file-input"}
    date_attr = {'type': "datetime", 'class': "form-control", "placeholder": 'YYYY-MM-DD ชั่วโมง:นาที'}
    desc_attr = {'class': "form-control" ,'rows': "3"}


    # bill_picture = forms.ImageField(label='อัพโหลดสลิป',
    #     widget=forms.TextInput(attrs=bill_attr))
    payment_datetime = forms.DateTimeField(
        widget=forms.DateInput(attrs=date_attr))
    payment_desc = forms.CharField(widget=forms.Textarea(attrs=desc_attr))
    bill_picture = forms.ImageField(label="อัพโหลดสลิป")
    # payment_datetime = forms.DateTimeField(
    #     label="วันเวลาโอนชำระเงิน", widget=forms.TextInput(attrs={'type': 'datetime'}))
    # payment_desc = forms.CharField(label="หมายเหตุ", required=False)

    class Meta:
        model = Payment
        exclude = ['payment_confirm', 'payment_guest_id', 'bill_picture']


class GuestReportForm(forms.ModelForm):
    desc_attr = {'class': "form-control", 'id': "detail", 'rows': "3"}

    report_desc = forms.CharField(widget=forms.Textarea(attrs=desc_attr))

    class Meta:
        model = Reporting
        exclude = ['report_date', 'report_type_type_id', 'room_room_id']

class GuestCreateForm(UserCreationForm):
    # declare the fields you will show
    username = forms.CharField(label="Your Username")
    # first password field
    # password1 = forms.CharField(label="Your Password")
    # confirm password field
    # password2 = forms.CharField(label="Repeat Your Password")
    email = forms.EmailField(label="Email Address")
    first_name = forms.CharField(label="Name")
    last_name = forms.CharField(label="Surname")
    address = forms.CharField(label="Address")
    line = forms.CharField(label="Line")
    phone = forms.CharField(label="Phone")

    class Meta:
        model = User
        fields = (
            "first_name", "last_name", "email", "username", "password1", "password2", "address", 'line', 'phone'
            )

    # this redefines the save function to include the fields you added
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        
        if commit:
            user.save()
        return user


class PaymentForm(forms.Form):
    bill_attr = {'type': "file", 'class': "custom-file-input"}
    date_attr = {'type': "datetime", 'class': "form-control"}
    desc_attr = {'class': "form-control" ,'rows': "3"}

    # bill_picture = forms.ImageField(label="อัพโหลดสลิป", widget=forms.TextInput(attrs=bill_attr))
    # payment_datetime = forms.DateTimeField(label="วันเวลาโอนชำระเงิน", widget=forms.TextInput(attrs=date_attr))
    # payment_desc = forms.CharField(label="หมายเหตุ", widget=forms.Textarea(attrs=desc_attr), required=False)
    bill_picture = forms.ImageField(label="อัพโหลดสลิป")
    payment_datetime = forms.DateTimeField(label="วันเวลาโอนชำระเงิน", widget=forms.TextInput(attrs={'type': 'datetime'}))
    payment_desc = forms.CharField(label="หมายเหตุ", required=False)

management/templates/member/annouce.html
{% extends "base.html" %} {% block content%}

<div class="container bg-white p-5 mt-4 contain">
    <h4 class="text-center mb-3"><i class="fas fa-bullhorn"></i> ประกาศ</h4>
    <div class="row">
        <div class="col-md-12">
            {%if show_news%} {% for new in anounce%}
            <div class="annouce p-3 my-2 bg-secondary text-white rounded">
                <i class="fas fa-exclamation-triangle text-warning"></i> <b>{{new.news_title}}</b> {{new.news_content}}
            </div>
            {%endfor%} {%endif%}
        </div>
    </div>
    <br><br>
    <h4 class="text-center mb-3"><i class="fas fa-box-open"></i> พัสดุ</h4>
    <div class="row">
        {% for parcel in parcels %}
        <div class="col-md-6">
            <div class="annouce p-3 my-2 bg-info text-white rounded">
                <i class="fas fa-box text-warning"></i> <b>{{parcel.arrive_date |date:'d-m'}}-{{parcel.year_now}} | </b> {{parcel.fname_guest}} {{parcel.lname_guest}}
            </div>
        </div>
        {%endfor%}


    </div>
</div>

{% endblock content%}

management/templates/member/bill.html
{% extends "base.html" %} {% block content%}

<div class="container bg-white p-5 contain">
    <h4 class="text-center mb-3">บิลล่าสุด</h4>
    <div class="row">
        <div class="col-sm-9">
            <h5>บิลประจำเดือน <span class="text-primary">{{indetails.0.0.invoice_invoice_id.month_now}}</span> ยอดชำระ <span class="text-danger">{{indetails.0.0.invoice_invoice_id.total|stringformat:".2f"}}</span> บาท
            </h5>
        </div>
        {%if invoicehis %}
        <div class="col-sm-3">
            {%if paid %}
            <a @click.prevent='' href="{% url 'user_bill' %}" class="btn btn-success">ชำระแล้ว</a>
            <!--  -->
            {%else%}
            <a href="{% url 'user_payment' %}" class="btn btn-danger">ยังไม่ชำระ</a>
            <!--  -->
            {%endif%}
            <a href="{% url 'user_detail' %}" class="btn btn-info" data-toggle="collapse" data-target="#detail_id" aria-expanded="false" aria-controls="collapseExample">รายละเอียด</a>
        </div>
        <!-- รายละเอียด -->
        <div class="col-12 border rounded p-3 mt-4 collapse" id="detail_id">
            <table width="100%">
                <tr>
                    <th width="50%">รายการ</th>
                    <th width="15%">จำนวน</th>
                    <th width="20%">ต่อหน่วย</th>
                    <th width="15%">จำนวนเงิน</th>
                </tr>
                <tr>
                    <td>ค่าเช่าห้องเดือน{{indetails.0.0.invoice_invoice_id.month_now}} {{indetails.0.0.invoice_invoice_id.year_now}}</td>
                    <td>1</td>
                    <td>{{room.room_rate|stringformat:".2f"}}</td>
                    <td>{{room.room_rate|stringformat:".2f"}}</td>
                </tr>
                {% for i in indetails.0%}
                <!--  -->
                <tr>
                    <td>{{i.expense_exp_id.exp_desc}}</td>
                    <td>{{i.unit|stringformat:"d"}}</td>
                    <td>{{i.expense_exp_id.price_per_unit|stringformat:".2f"}}</td>
                    <td>{{i.total|stringformat:".2f"}}</td>
                </tr>
                <!--  -->
                {% endfor %}
                <tr>
                    <td colspan="3">จำเงินรวมทั้งสิ้น</td>
                    <td>{{indetails.0.0.invoice_invoice_id.total|stringformat:".2f"}}</td>
                </tr>
            </table>
        </div>
        <!-- รายละเอียด -->
        {%endif%}
    </div>
</div>

<div class="container bg-white p-5 my-4 contain">
    <h4 class="mb-3 text-center">ประวัติการชำระเงิน</h4>
    <br> {%if invoicehis %}
    <!--add if invoice later ---------- -->
    {% for details in indetails %}
    <div class="row mt-3">
        <div class="col-sm-2 font-weight-bold">{{details.0.invoice_invoice_id.month_now}} {{details.0.invoice_invoice_id.year_now}}</div>
        <div class="col-sm-2">{{details.0.expense_exp_id.exp_desc}} {{details.0.unit|stringformat:"d"}} หน่วย</div>
        <div class="col-sm-2">{{details.1.expense_exp_id.exp_desc}} {{details.1.unit|stringformat:"d"}} หน่วย</div>
        <div class="col-sm-2 text-primary font-weight-bold">{{details.0.invoice_invoice_id.total|stringformat:".2f"}} บาท</div>
        <div class="col-sm-4 buttop"><button class="btn btn-outline-primary w-100" data-toggle="collapse" data-target="#detail_id{{details.0.invoice_invoice_id_id}}" aria-expanded="false" aria-controls="detail_id2">ดูรายละเอียด</button></div>
    </div>
    <!-- รายละเอียด -->
    <div class="col-12 border rounded p-3 mt-4 collapse" id="detail_id{{details.0.invoice_invoice_id_id}}">
        <table width="100%">
            <tr>
                <th width="50%">รายการ</th>
                <th width="15%">จำนวน</th>
                <th width="20%">ต่อหน่วย</th>
                <th width="15%">จำนวนเงิน</th>
            </tr>
            <tr>
                <td>ค่าเช่าห้อง{{details.0.invoice_invoice_id.month_now}} {{details.0.invoice_invoice_id.year_now}}</td>
                <td>1</td>
                <td>{{room.room_rate|stringformat:".2f"}}</td>
                <td>{{room.room_rate|stringformat:".2f"}}</td>
            </tr>
            {% for d in details %}
            <tr>
                <td>{{d.expense_exp_id.exp_desc}}</td>
                <td>{{d.unit|stringformat:"d"}}</td>
                <td>{{d.expense_exp_id.price_per_unit|stringformat:".2f"}}</td>
                <td>{{d.total|stringformat:".2f"}}</td>
            </tr>
            {%endfor%}
            <tr>
                <td colspan="3">จำเงินรวมทั้งสิ้น</td>
                <td>{{details.0.invoice_invoice_id.total|stringformat:".2f"}}</td>
            </tr>
        </table>
    </div>
    <!-- รายละเอียด -->
    {% endfor %} {%endif%}

    <!-- <div class="row mt-3">
        <div class="col-sm-2 font-weight-bold">มีนาคม 2562</div>
        <div class="col-sm-2">ค่าไฟ 56 หน่วย</div>
        <div class="col-sm-2">ค่าน้ำ 3 หน่วย</div>
        <div class="col-sm-2 text-primary font-weight-bold">6105.00 บาท</div>
        <div class="col-sm-4 buttop"><button class="btn btn-outline-primary w-100" data-toggle="collapse" data-target="#detail_id2" aria-expanded="false" aria-controls="detail_id2">ดูรายละเอียด</button></div>
    </div>

    <div class="row mt-3">
        <div class="col-sm-2 font-weight-bold">กุมภาพันธ์ 2562</div>
        <div class="col-sm-2">ค่าไฟ 47 หน่วย</div>
        <div class="col-sm-2">ค่าน้ำ 2 หน่วย</div>
        <div class="col-sm-2 text-primary font-weight-bold">5830.00 บาท</div>
        <div class="col-sm-4 buttop"><button class="btn btn-outline-primary w-100" data-toggle="collapse" data-target="#detail_id2" aria-expanded="false" aria-controls="detail_id2">ดูรายละเอียด</button></div>
    </div>

    <div class="row mt-3">
        <div class="col-sm-2 font-weight-bold">มกราคม 2562</div>
        <div class="col-sm-2">ค่าไฟ 21 หน่วย</div>
        <div class="col-sm-2">ค่าน้ำ 1 หน่วย</div>
        <div class="col-sm-2 text-primary font-weight-bold">5310.00 บาท</div>
        <div class="col-sm-4 buttop"><button class="btn btn-outline-primary w-100" data-toggle="collapse" data-target="#detail_id2" aria-expanded="false" aria-controls="detail_id2">ดูรายละเอียด</button></div>
    </div> -->

</div>


{% endblock content%}

management/templates/member/contract.html
{% extends "base.html" %} {% block content%}

<!-- code here -->

<div class="container bg-white p-5 mt-4 contain">
    <h2 class="text-center">สัญญาหอพัก</h2>
    <br>
    <p>เริ่มสัญญาวันที่ {{contract.day_now_str}} {{contract.month_now_str}} {{contract.year_now_str}}</p>
    <p>หมดสัญญาวันที่ {{contract.day_now_end}} {{contract.month_now_end}} {{contract.year_now_end}}</p>
</div>

<div class="container bg-white p-5 contain mt-5">
    <h2 class="text-center">ข้อมูลหอพัก</h2>
    <br>
    <p>
        <b>ที่อยู่หอพัก: </b> {{dorm.location}}
    </p>
    <p>
        <b>เบอร์โทรหอพัก: </b> {{dorm.tel}}
    </p>
    <!-- <p>
        <b>เวลาทำการ Office: </b> 9.00 - 17.00 น. (ปิดทุกวันอาทิตย์)
    </p>
    <p>
        <b>หมายเหตุ: </b> กรุณาระบุเลขห้องพักในการจัดส่งพัสดุด้วย
    </p> -->
</div>


{% endblock content%}

management/templates/member/detail.html
{% extends "base.html" %} {% block content%}

<!-- code here -->

{% endblock content%}

management/templates/member/index.html
{% extends "base.html" %} {% block content %}

<div class="container bg-white p-5 contain">
    <br>
    <center>
        <h1 style="font-size: 6em;"><i class="fas fa-building"></i></h1>
        <br>
        <h1 style="font-size: 4em;">Welcome, Room {{room.room_number}}</h1>
        <h5>@ {{dorm.dorm_name}}</h5>
        <br> {%if unpaid %}
        <div class="annouce p-3 my-2 bg-danger text-white rounded">
            <i class="fas fa-exclamation-triangle text-warning"></i> ยอดค้างชำระเดือน {{invoice.month_now}} {{invoice.year_now}} จำนวน {{invoice.total|stringformat:".2f"}} บาท
        </div>
        {%endif%}
        <br>
    </center>
</div>

{% endblock content %}

management/templates/member/payment.html
{% extends "base.html" %} {% block content%}

<!-- new Dorm -->
<div class="container bg-white p-5 contain">
    <div class="d-flex justify-content-center">
        <h1 class="mx-auto mb-4">แจ้งชำระเงิน</h1>
    </div>

    <form method='POST' enctype="multipart/form-data" action="{% url 'user_payment' %}">
        {%csrf_token%}

        <!-- Notification -->
        {% if messages %}
        <!--  -->
        {%for message in messages%}
        <div class="noti">
            <div class="alert alert-success text-center" role="alert">
                <i class="far fa-check-circle"></i> ส่งสำเร็จเรียบร้อย
            </div>
            <!-- <div class="alert alert-danger z-index-100" role="alert">
                <i class="far fa-times-circle"></i> ผิดพลาด ลองใหม่อีกครั้งหรือติดต่อเจ้าของหอพักเพื่อแจ้งปัญหา
            </div> -->
        </div>
        <!--  -->
        {%endfor%}
        <!--  -->
        {%endif%}
        <!-- / Notification -->

        <div class="form-group">
            <label for="name"><i class="fas fa-user"></i> ชื่อ-สกุล</label>
            <input type="text" class="form-control" value="{{user.first_name}} {{user.last_name}}" id="name" disabled>
        </div>

        <div class="form-group">
            <label for="room"><i class="fas fa-door-closed"></i> ห้องพัก</label>
            <input type="text" class="form-control" value="{{room.room_number}}" id="room" disabled>
        </div>

        <div class="form-group">
            <label for="price"><i class="fas fa-money-bill-alt"></i> จำนวนเงิน</label>
            <!--  -->
            {%if paid%}
            <input type="number" class="form-control text-danger" value='0.00' id="price" disabled>
            <!--  -->
            {%else%}
            <input type="number" class="form-control text-danger" value='{{invoice.total|stringformat:".2f"}}' id="price" disabled>
            <!--  -->
            {%endif%}
        </div>
        <div class="form-group">
            <label id="{{ form.bill_picture.id_for_label }}" for="phonefordorm"><i class="fas fa-cloud-upload-alt"></i> {{form.bill_picture.label}}</label>
            <div class="custom-file">
                <input name='bill_picture' type="file" class="custom-file-input" id="customFile">
                <!-- {{form.bill_picture}} -->
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
        </div>

        <div class="form-group">
            <label for="id_payment_datetime"><i class="far fa-calendar-alt"></i> วันเวลาโอนชำระเงิน</label>
            <!-- <input type="datetime-local" class="form-control" id="taxid"> -->
            {{ form.payment_datetime}}
        </div>

        <div class="form-group">
            <label for="id_payment_desc"><i class="fas fa-comment"></i> หมายเหตุ</label>
            <!-- <input type="textarea" class="form-control" id="notice" rows="30" cols='70'> -->
            {{form.payment_desc}}
            <!-- <textarea class="form-control" id="notice" rows="3"></textarea> -->
        </div>

        <div class="d-flex justify-content-center">
            {%if paid %}
            <button type="submit" class="btn btn-primary w-100 mt-3" disabled>ยันยัน</button>
            <!--  -->
            {%else%}
            <button type="submit" class="btn btn-primary w-100 mt-3">ยันยัน</button>
            <!--  -->
            {%endif%}
        </div>
    </form>
</div>
<!-- / new Dorm -->

<script>
    $('#customField').on('change', function() {
        var fileName = $(this).val();
        $(this).next('.custom-file-label').html(fileName);
    })
</script>
{% endblock content%}

management/templates/member/template.html
{% extends "base.html" %} {% block content%}

<!-- code here -->

{% endblock content%}